// represent a submission to the service
export class Submission {
    // the submission id. generated by the db
    id?: number; 
    // the account submitted
    account_id:number; 
    // the name of the submission
    name: string; 
    // the submission status (CREATED,IN PROCESS,DONE)
    status:number; 
    // the input file name
    filename: string;
    // when the submission was created  
    created?:Date; 
    // when execution was started
    started?:Date; 
    // when execution ended
    ended?:Date; 
    // the location of the final report
    report_location?:string 
    // what is the optimal machine learning algorithm
    best_alg?: string;
    // the best alg parameters
    best_alg_param?: string;
    // what is the optimal f1 
    best_f1?: number; 
    // what is the optimal accuracy
    best_accuracy?: number; 
    // what is the optimal recall
    best_recall?:number 
    // what is the optimal precision
    best_precision?:number 
    // what is the optimal precision
    lastUpdated?:Date 
    
}